BP/BP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls')),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('profiles/', include('profiles.urls')),
    path('imageconvert/', include('imageconvert.urls', namespace='imageconvert')),
    path('goods/', include('goods.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BP/accounts/urls.py
from django.urls import path
from django.urls import path, include
# from .views import home_screen_view
from accounts.views import signup, login, logout, detail, update, password_change, delete

app_name = 'accountsapp'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('detail/<int:pk>/', detail, name='detail'),
    path('update/<int:pk>/', update, name='update'),
    path('delete/', delete, name='delete'),
    path('password/<int:pk>', password_change, name='password'),
]

BP/goods/urls.py
from django.urls import path, include
from goods.views import makegoods, downloadFile_hp, downloadFile_gr, downloadFile_kr, downloadFile_ts


app_name = 'goods'

urlpatterns = [
    path("download_hp/", downloadFile_hp, name="downloadFile_hp"),
    path("download_gr/", downloadFile_gr, name="downloadFile_gr"),
    path("download_kr/", downloadFile_kr, name="downloadFile_kr"),
    path("download_ts/", downloadFile_ts, name="downloadFile_ts"),
    path('goodssample/', makegoods, name='makegoods'),
]

BP/imageconvert/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'imageconvert'
urlpatterns = [
    path('viewimage', views.viewimage, name='viewimage'),
    path('download', views.downloadFile, name='downloadFile'),
    path('', views.imageconvert),
]

BP/loading/urls.py
from django.urls import path
from loading.views import loading

app_name = 'loading'

urlpatterns = [
    path('', loading, name='loading'),
]

BP/imageconvert/models.py
from django.db import models
from io import *
from django.core.files.uploadedfile import InMemoryUploadedFile
import sys
from django.conf import settings
from accounts.models import Account

class Images(models.Model):
    # Image_id = models.AutoField()
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    raw_img = models.ImageField(upload_to='raw_img/', null=True)
    cvt_img = models.ImageField(upload_to='cvt_img/', null=True)

BP/loading/models.py
from django.db import models

# Create your models here.

BP/imageconvert/views.py
from django.shortcuts import render, redirect
from .models import *
import numpy as np
import cv2, joblib,sys
from datetime import datetime
import logging
import string
import os
import tf_slim as slim
import tensorflow.compat.v1 as tf
from django.http import FileResponse
from django.core.files.storage import FileSystemStorage
from pathlib import Path
from tqdm import tqdm
from pathlib import Path
from accounts.models import Account
from rembg import remove
from rembg import remove1
from rembg import remove2
from PIL import Image, ImageOps, ImageFilter
from django.contrib.auth.decorators import login_required
from django.contrib import messages
# -*- coding:utf-8 -*-


global output1
def rembg(in_img):  #input_img: 원본 이미지 경로 /  output_img: 저장 경로 / white_img: 흰 배경 이미지 경로
    
  input_path = in_img
  input = Image.open(input_path).convert("RGBA")
  #input = resize_crop(input)
  test1 = remove1(input)
  print("TEST1")
  print(type(test1))
  #print(test1)   
  output = remove2(input,test1)
  
  print("TEST2")
  print(type(output))
  
  ROOT_PATH = str(Path(__file__).resolve().parent.parent)
  background = Image.open(ROOT_PATH + '\\static\\img\\design\\white.jpg')
  logging.warning(background)
  
  foreground = output
  (img_h, img_w) = foreground.size
  resize_back =  background.resize((img_h, img_w))
  resize_back.paste(foreground, (0, 0), foreground)
  img = np.array(resize_back)

  image_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
  #b,g,r = cv2.split(img)

  blur = cv2.GaussianBlur(image_gray, ksize=(5,5), sigmaX=0)
  #ret, thresh1 = cv2.threshold(blur, 127, 255, cv2.THRESH_BINARY)
  edged = cv2.Canny(blur, 10, 250)
  kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (7,7))
  closed = cv2.morphologyEx(edged, cv2.MORPH_CLOSE, kernel)
  contours, _ = cv2.findContours(closed.copy(),cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
  #total=0
  contours_xy = np.array(contours)
  contours_xy.shape
  x_min, x_max = 0,0
  value = list()
  for i in range(len(contours_xy)):
      for j in range(len(contours_xy[i])):
          value.append(contours_xy[i][j][0][0])
          x_min = min(value)
          x_max = max(value)


  y_min, y_max = 0,0
  value = list()
  for i in range(len(contours_xy)):
      for j in range(len(contours_xy[i])):
          value.append(contours_xy[i][j][0][1])
          y_min = min(value)
          y_max = max(value)


  x = x_min
  y = y_min
  w = x_max-x_min
  h = y_max-y_min
  return test1, x,y,w,h
  #fi_img = output.crop((x,y,x+w,y+h))
  #fi_img.save(output_img)
  #return output_img
    


def resize_crop(image):
    h, w, c = np.shape(image)
    if min(h, w) > 720:
        if h > w:
            h, w = int(720*h/w), 720
        else:
            h, w = 720, int(720*w/h)
    image = cv2.resize(image, (w, h),
                       interpolation=cv2.INTER_AREA)
    h, w = (h//8)*8, (w//8)*8
    image = image[:h, :w, :]
    return image

def tf_box_filter(x, r):
    k_size = int(2*r+1)
    ch = x.get_shape().as_list()[-1]
    weight = 1/(k_size**2)
    box_kernel = weight*np.ones((k_size, k_size, ch, 1))
    box_kernel = np.array(box_kernel).astype(np.float32)
    output = tf.nn.depthwise_conv2d(x, box_kernel, [1, 1, 1, 1], 'SAME')
    return output

def guided_filter(x, y, r, eps=1e-2):
    
    x_shape = tf.shape(x)
    #y_shape = tf.shape(y)

    N = tf_box_filter(tf.ones((1, x_shape[1], x_shape[2], 1), dtype=x.dtype), r)

    mean_x = tf_box_filter(x, r) / N
    mean_y = tf_box_filter(y, r) / N
    cov_xy = tf_box_filter(x * y, r) / N - mean_x * mean_y
    var_x  = tf_box_filter(x * x, r) / N - mean_x * mean_x

    A = cov_xy / (var_x + eps)
    b = mean_y - A * mean_x

    mean_A = tf_box_filter(A, r) / N
    mean_b = tf_box_filter(b, r) / N

    output = mean_A * x + mean_b

    return output    

def resblock(inputs, out_channel=32, name='resblock'):
    
    with tf.variable_scope(name):
        
        x = slim.convolution2d(inputs, out_channel, [3, 3], 
                               activation_fn=None, scope='conv1')
        x = tf.nn.leaky_relu(x)
        x = slim.convolution2d(x, out_channel, [3, 3], 
                               activation_fn=None, scope='conv2')
        
        return x + inputs

def unet_generator(inputs, channel=32, num_blocks=4, name='generator', reuse=False):
    with tf.variable_scope(name, reuse=reuse):
        
        x0 = slim.convolution2d(inputs, channel, [7, 7], activation_fn=None)
        x0 = tf.nn.leaky_relu(x0)
        
        x1 = slim.convolution2d(x0, channel, [3, 3], stride=2, activation_fn=None)
        x1 = tf.nn.leaky_relu(x1)
        x1 = slim.convolution2d(x1, channel*2, [3, 3], activation_fn=None)
        x1 = tf.nn.leaky_relu(x1)
        
        x2 = slim.convolution2d(x1, channel*2, [3, 3], stride=2, activation_fn=None)
        x2 = tf.nn.leaky_relu(x2)
        x2 = slim.convolution2d(x2, channel*4, [3, 3], activation_fn=None)
        x2 = tf.nn.leaky_relu(x2)
        
        for idx in range(num_blocks):
            x2 = resblock(x2, out_channel=channel*4, name='block_{}'.format(idx))
            
        x2 = slim.convolution2d(x2, channel*2, [3, 3], activation_fn=None)
        x2 = tf.nn.leaky_relu(x2)
        
        h1, w1 = tf.shape(x2)[1], tf.shape(x2)[2]
        x3 = tf.image.resize_bilinear(x2, (h1*2, w1*2))
        x3 = slim.convolution2d(x3+x1, channel*2, [3, 3], activation_fn=None)
        x3 = tf.nn.leaky_relu(x3)
        x3 = slim.convolution2d(x3, channel, [3, 3], activation_fn=None)
        x3 = tf.nn.leaky_relu(x3)

        h2, w2 = tf.shape(x3)[1], tf.shape(x3)[2]
        x4 = tf.image.resize_bilinear(x3, (h2*2, w2*2))
        x4 = slim.convolution2d(x4+x0, channel, [3, 3], activation_fn=None)
        x4 = tf.nn.leaky_relu(x4)
        x4 = slim.convolution2d(x4, 3, [7, 7], activation_fn=None)
        
        return x4

@login_required
def imageconvert(request):
    return render(request, 'imageconvert.html')

def downloadFile(request):
    image = Images.objects.last()
    f_image = image.cvt_img.url
    file_name = os.path.dirname(os.path.abspath(os.path.dirname(__file__))) + f_image
    fs = FileSystemStorage(file_name)
    response = FileResponse(fs.open(file_name, 'rb'), content_type='image/png')
    response['Content-Disposition'] = f'attachment; filename={os.path.basename(f_image)}'
    return response

logger = logging.getLogger('mylogger')

def cartoonize(model_path, load_path, save_path):
    try:
        tf.disable_eager_execution()
    except:
        None

    tf.reset_default_graph()
    #ROOT_PATH = str(Path(__file__).resolve().parent.parent)
    input_photo = tf.placeholder(tf.float32, [1, None, None, 3])
    #input_photo = Image.open(ROOT_PATH + '\\static\\img\\cat.jpg')
    network_out = unet_generator(input_photo)
    final_out = guided_filter(input_photo, network_out, r=1, eps=5e-3)

    all_vars = tf.trainable_variables()
    gene_vars = [var for var in all_vars if 'generator' in var.name]
    saver = tf.train.Saver(var_list=gene_vars)
    
    config = tf.ConfigProto()
    config.gpu_options.allow_growth = True
    sess = tf.Session(config=config)

    sess.run(tf.global_variables_initializer())
    saver.restore(sess, tf.train.latest_checkpoint(model_path))
    # load_path = os.path.join(Path(__file__).resolve().parent.parent, 'test_images')
    # save_path = os.path.join(Path(__file__).resolve().parent.parent, 'cartoonized_images')
    
    img_array = np.fromfile(load_path, np.uint8)
    image = cv2.imdecode(img_array, cv2.IMREAD_COLOR)
    image = resize_crop(image)
    temp = Image.fromarray(image) # 여기서 배열에 들어있는 이미지가 리사이즈된 상태로 배경 자르는 코드로 넘겨짐
    batch_image = image.astype(np.float32)/127.5 - 1
    batch_image = np.expand_dims(batch_image, axis=0)
    output = sess.run(final_out, feed_dict={input_photo: batch_image})
    output = (np.squeeze(output)+1)*127.5
    output = np.clip(output, 0, 255).astype(np.uint8)
    cv2.imwrite(save_path, output)
    
    #region 여기서 이미지 마스크 따기
    input = temp.convert("RGBA") # 배열에 담긴 이미지를 변환해서 이 리전에서 마스크값으로 바꿔줌
    test1 = remove1(input)
    output = remove2(input,test1)
    ROOT_PATH = str(Path(__file__).resolve().parent.parent)
    background = Image.open(ROOT_PATH + '\\static\\img\\design\\white.jpg')
    logging.warning(background)    
    foreground = output
    (img_h, img_w) = foreground.size
    resize_back =  background.resize((img_h, img_w))
    resize_back.paste(foreground, (0, 0), foreground)
    img = np.array(resize_back)
    image_gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)  
    blur = cv2.GaussianBlur(image_gray, ksize=(5,5), sigmaX=0)
    edged = cv2.Canny(blur, 10, 250)
    kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (7,7))
    closed = cv2.morphologyEx(edged, cv2.MORPH_CLOSE, kernel)
    contours, _ = cv2.findContours(closed.copy(),cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
    contours_xy = np.array(contours)
    contours_xy.shape
    x_min, x_max = 0,0
    value = list()
    for i in range(len(contours_xy)):
      for j in range(len(contours_xy[i])):
          value.append(contours_xy[i][j][0][0])
          x_min = min(value)
          x_max = max(value)


    y_min, y_max = 0,0
    value = list()
    for i in range(len(contours_xy)):
        for j in range(len(contours_xy[i])):
            value.append(contours_xy[i][j][0][1])
            y_min = min(value)
            y_max = max(value)
    x = x_min
    y = y_min
    w = x_max-x_min
    h = y_max-y_min
    
    
      #endregion 
    return output, test1, x,y,w,h # 이미지랑 마스크값 리턴

def viewimage(request):
    if request.method == 'POST' and request.FILES.get('files'):
        file = request.FILES['files']
        images = Images()
        images.user_id = request.user
        images.raw_img = file
        images.save()
        model_select = request.POST.get('model_select')
        load_path = images.raw_img.path
        ROOT_PATH = str(Path(__file__).resolve().parent.parent)
        img_name = load_path.split('\\')[-1]

        src = os.path.splitext(img_name)

BP/loading/views.py
from django.shortcuts import render

# Create your views here.
def loading(request):
    return render(request, 'loading.html')

BP/templates/base.html
{% load static %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
<link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
<!doctype html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="icon" href="{% static 'img/favicon.ico' %}">
    <title>인생굿즈</title>
</head>
<body>
    <div class="wrap">
        <nav id="navbar" class="navbar navbar-default navbar-expand-sm fixed-top bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">
                    <img href="/" src="{% static 'img/Logo.png' %}" alt="" width="100" height="50">
                    {% comment %} <span class="fs-1 mx-3">인생굿즈</span> {% endcomment %}
                </a>
                <button class="navbar-toggler" type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent"
                        aria-expanded="false"
                        aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link" href="/imageconvert/" >굿즈 만들기</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/article/">공유 게시판</a>
                        </li>
                        {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <div class="btn-group h-100 align-items-center">
                                <button style="border: none; background:none;" type="button" class="dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                    <img style="height:3rem; width:3rem; border-radius:1.5rem;" src="{{request.user.profile.image.url}}  " alt="">
                                </button>
                                <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="{% url 'accountsapp:detail' user.pk %}">내 정보</a></li>
                                <li><a class="dropdown-item" href="{% url 'accountsapp:logout' %}">로그아웃</a></li>
                                </ul>
                            </div>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'accountsapp:login' %}">로그인</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
        <div class='container'>
            <!-- 채울 부분 -->
            {% block content%}

            {% endblock %}
        </div>
        <div class='footer'>
            <div class="extra">
                <span>고객센터 Tel.062-522-0989</span> |
                <span>Made by. 연봉 19조(강병국, 김예지, 문강현, 문지호, 박현종, 순수연, 표동우)</span>
            </div>
        </div>
    </div>
</body>
</html>

BP/templates/makegoods.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="content">
        <!doctype html>
        <html lang="ko">
        <head>            
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            {% comment %} <title>Bootstrap 4</title> {% endcomment %}
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
            <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
            <style>
                .nav-pills > .nav-item > .active {
                    color: rgb(0, 0, 0) !important;
                    background-color : #dde6ff !important;
                    border-radius: 5px 5px 0px 0px;
                }
                .center {
                    display: flex;
                    justify-content: center;
                }
                .tab-content{
                    background-color: #dde6ff !important;
                }
                .detail_body{
                    display: block;
                    width: 100%;
                    padding: 0.375rem 0.75rem;
                    font-size: 1rem;
                    font-weight: 400;
                    line-height: 1.5;
                    background-color: #fff;
                    background-clip: padding-box;
                    border: 1px solid #ced4da;
                    border-radius: 0.25rem;
                }
                .b_info{
                    height:50px;
                    background-color: #b5c8ff;
                    margin:0 0 0 0;
                }
                .b_info>span{
                    float:right;
                    padding-right:1.5rem;
                }
                hr{
                    background-color: #b5c8ff;
                }
                .dwn_btn {
                    background-color: #6288f9;
                    color: #fff;
                    text-align: center;
                    border-radius: 6px;
                    cursor: pointer;
                    border:none;
                    padding:0.25rem;
                }
                .move_btn{
                    color:black;
                    background-color: #eeeeee;
                    cursor: pointer;
                    border:none;
                    font-size:1.2rem;
                }
                .move_btn:hover{
                    color:#285eff;
                    text-decoration:underline;
                }
            </style>
            <script> 
                function btn1(){
                    swal({
                        title:'메인으로 이동할까요?',
                        text: "",
                        icon:"info",
                        buttons: ["아니오", "네"]
                    }).then(function(result){
                        if(result){
                            swal({title:"메인", text:"메인으로 이동합니다."
                            }).then((value) => {
                                if(value){
                                    window.location.href='/';
                                }
                            })
                        }
                    })
                    /*if (confirm("메인으로 이동할까요?")) {                        
                        location.href='/';
                    }*/
                }
                function btn2(){
                    swal({
                        title:'게시글 작성으로 이동할까요?',
                        text: "",
                        icon:"info",
                        buttons: ["아니오", "네"]
                    }).then(function(result){
                        if(result){
                            swal({title:"게시글 작성", text:"게시글 작성으로 이동합니다."
                            }).then((value) => {
                                if(value){
                                    window.location.href='/article/create';
                                }
                            })
                        }
                    })
                    /*if (confirm("게시글 작성으로 이동할까요?")) {                        
                        location.href='/article/create';
                    }*/
                }
            </script> 
        </head>
        <body style='padding-top: 80px;height: 100%;background-color: rgb(242, 245, 255);'>
            <div class="container-fluid">
                <div class='detail_body' style='float:right;width=90%;'>
                    <div style='margin-top: 1rem!important'>
                        <h3>굿즈 만들기</h3>
                    </div>
                    <div class='b_info'>
                        <hr />
                        <span>굿즈 만들기 > 굿즈 샘플 도안</span>
                        <hr />
                    </div>
                    <div style="padding-top:0px; width:760;" class="container">
                    <div class="row" style='margin-top:2rem;'>
                        <div class="col">
                            <ul class="nav nav-pills center">
                            <li class="nav-item">
                                <a class="nav-link active" data-toggle="tab" href="#hp">핸드폰케이스</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#gt">그립톡</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#kr">키링</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" data-toggle="tab" href="#ts">티셔츠</a>
                            </li>
                            </ul>
                            <div style=" padding:30px; background-color: #007BFF; border-radius:5px; height:400px;" class="tab-content center">
                            <div class="tab-pane fade show active" id="hp">
                                <div>
                                    <img src='{{ design.design_hp.url }}' alt="" width="300" height="300">
                                </div>
                                <div style="margin-top:10; text-align: center;">
                                    <form action="{% url 'goods:downloadFile_hp'  %}">
                                        <button style="padding:5px; border-radius:5px;" onclick="" class='dwn_btn'><i class="bi bi-arrow-down"></i>&nbsp;다운로드</button>
                                    </form>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="gt">
                                <div>
                                    <img href="/" src="{{ design.design_gr.url }}" alt="" width="300" height="300">
                                </div>
                                <div style="margin-top:10; text-align: center;">
                                    <form action="{% url 'goods:downloadFile_gr'  %}">
                                        <button style="padding:5px; border-radius:5px;" onclick="" class='dwn_btn'><i class="bi bi-arrow-down"></i>&nbsp;다운로드</button>
                                    </form>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="kr">
                                <div>
                                    <img href="/" src="{{ design.design_kr.url }}" alt="" width="300" height="300">
                                </div>
                                <div style="margin-top:10; text-align: center;">
                                    <form action="{% url 'goods:downloadFile_kr'  %}">
                                        <button style="padding:5px; border-radius:5px;" onclick="" class='dwn_btn'><i class="bi bi-arrow-down"></i>&nbsp;다운로드</button>
                                    </form>
                                </div>
                            </div>
                            <div class="tab-pane fade" id="ts">
                                <div>
                                    <img href="/" src="{{ design.design_ts.url }}" alt="" width="300" height="300">
                                </div>
                                <div style="margin-top:10; text-align: center;">
                                    <form action="{% url 'goods:downloadFile_ts'  %}">
                                        <button style="padding:5px; border-radius:5px;" onclick="" class='dwn_btn'><i class="bi bi-arrow-down"></i>&nbsp;다운로드</button>
                                    </form>
                                </div>
                            </div>
                            </div>
                        </div>
                        <div style="padding-right:15; margin-top:10px; text-align:left;width:50%;">
                            <div class="btn-group" style='text-align:left;'>
                                <button type="button" style="padding:5px; border-radius:5px; margin-right:3px;" class="move_btn" data-toggle="dropdown"><i class="bi bi-basket-fill"></i>&nbsp;굿즈 제작하러 가기</button>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="https://www.marpple.com/kr/product/list/84?cate_item_id=269&ordering=no?utm_source=goole&utm_medium=cpc_sa&utm_campaign=sticker&utm_term=%EA%B5%BF%EC%A6%88%20%EC%8A%A4%ED%8B%B0%EC%BB%A4%20%EC%A0%9C%EC%9E%91&gclid=Cj0KCQiAnsqdBhCGARIsAAyjYjTYYDhGbHgmYAQqHg5tKzXOXarO4UwnGjz3rmPya_oaVCgBo8g3uhUaAqjDEALw_wcB">마플</a>
                                    <a class="dropdown-item" href="https://wowpress.co.kr/ordr/prod/list?ProdNo=30008&linkProdNo=40152&ldtype=pd">와우프레스</a>
                                  </div>
                            </div>
                        </div>
                        <div style="padding-right:15; margin-top:10px; text-align:right;width:50%;">
                            <button style="padding:5px; border-radius:5px; margin-right:3px;" onclick="javascript:btn1()" class='move_btn'><i class="bi bi-house-door-fill"></i>&nbsp;메인</button>
                            <button style="padding:5px; border-radius:5px;" onclick="javascript:btn2()" class='move_btn'><i class="bi bi-pencil-square"></i> 내 굿즈 자랑 </button>
                        </div>                
                    </div>
                    </div>
                </div>
            </div>
            <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
        </body>
        </html>
    </div>
{% endblock %}