BP/BP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls')),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('profiles/', include('profiles.urls')),
    path('imageconvert/', include('imageconvert.urls', namespace='imageconvert')),
    path('goods/', include('goods.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BP/accounts/urls.py
from django.urls import path
from django.urls import path, include
# from .views import home_screen_view
from accounts.views import signup, login, logout, detail, update, password_change, delete

app_name = 'accountsapp'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('detail/<int:pk>/', detail, name='detail'),
    path('update/<int:pk>/', update, name='update'),
    path('delete/', delete, name='delete'),
    path('password/<int:pk>', password_change, name='password'),
]

BP/article/urls.py
from django.urls import path

from . import views

app_name = 'articleapp'

urlpatterns = [
    path('create/', views.CreatePost, name='CreatePost'),
    path('detail/<int:postid>', views.DetailPost, name='DetailPost'),
    path('delete/<int:postid>', views.DeletePost, name='DeletePost'),
    path('update/<int:postid>', views.UpdatePost, name='UpdatePost'),
    path('createcomment/<int:postid>', views.CreateComment, name='CreateComment'),
    path('updatecomment/', views.UpdateComment, name='UpdateComment'),
    path('deletecomment/<int:postid>/<int:commentid>', views.DeleteComment, name='DeleteComment'),
    path('', views.ListPost, name='ListPost'),
]

BP/profiles/urls.py
from django.urls import path
from profiles.views import update, mydesign

app_name = 'profilesapp'

urlpatterns = [
    path('update/<int:pk>/', update, name='update'),
    path('mydesign/', mydesign, name='mydesign'),
]

BP/profiles/models.py
from django.db import models
from accounts.models import Account
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(Account, on_delete=models.CASCADE,
                                related_name='profile')
    image = models.ImageField(upload_to='profile/', default='../static/img/user.jpg', blank=True)
    message = models.TextField(max_length=300, default='자기소개를 입력해주세요!', blank=True)
    
    @property
    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url
        else:
            return "static/img/user.jpg"
            

@receiver(post_save, sender=Account)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=Account)
def create_user_profile(sender, instance, **kwargs):
    instance.profile.save()
    

BP/profiles/forms.py
from django import forms
from profiles.models import Profile


class ProfileForm(forms.ModelForm):
    
    class Meta:
        model = Profile
        fields = ['image', 'message']
        widgets = {
            'image': forms.FileInput(attrs={
                'type': 'file',
                'id': 'image',
                'onchange': 'setThumbnail(event)',
                'style': 'margin-left: 200px'
            }),
        }

BP/profiles/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from profiles.models import Profile
from profiles.forms import ProfileForm
from article.models import Post, PostImage
from django.core.paginator import Paginator
from django.contrib import messages


@login_required
def update(request, pk):
    print(pk)
    profile=get_object_or_404(Profile, pk=pk)
    if request.user == profile.user:
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if request.method=='POST':
            if form.is_valid():
                profile.image = form.cleaned_data['image']
                profile.message = form.cleaned_data['message']
                profile.save()
                messages.success(request,"성공적으로 수정되었습니다.")
                return redirect('accountsapp:detail', profile.user.pk)
        else:
            messages.warning(request,"다시 입력하세요")
            form = ProfileForm(instance=profile)

        context={
            'form': form
        }
        return render(request,'profiles/update.html', context)
    else:
        messages.warning(request,"작성자가 아닙니다.")
        return redirect('accountsapp:detail', pk)

@login_required
def mydesign(request):
    post_list = Post.objects.filter(Board_writer_id=request.user.id).order_by('-Board_datetime')

    return render(request, 'profiles/MyDesign.html', {'post_list': post_list})

BP/profiles/templates/profiles/MyDesign.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link href="{% static 'css/main/style_mydesign.css' %}" rel="stylesheet">
<link href="{% static 'css/main/style_main.css' %}" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
<div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-md-4 bd-sidebar">
            <div class="bd-sidebar-body">
                <ul class="nav">
                    <li><a href="/profiles/mydesign" class="btn btn-lg mt-5" role="button">나의 디자인</a></li>
                    <li><a href="{% url 'accountsapp:detail' user.pk %}" class="btn btn-lg mt-5" role="button">개인 정보 수정</a></li>
                </ul>
            </div>
        </div>
        <div  class="MainGrid__StyledGrid-sc-1u1dl1e-0 gHAcDL styled-grid">
            {% if post_list %}
            <div class="row row-cols-3 row-cols-md-3 mb-3 center pt-5" style="width: 1000px;">
                {% for post in post_list %}
                    <div class="col-3">
                        <div class="card mb-4 shadow-sm">
                            <div id="carouselSlides" class="carousel slide" data-bs-ride="carousel">
                                <div class="carousel-inner">
                                    {% for image in post.postimage.all %}
                                        <div class="carousel-item {% if forloop.counter == 1 %} active {% endif %}" data-bs-interval="3000">
                                            <a href="{% url 'articleapp:DetailPost' post.Board_id %}">
                                                <img class="d-block w-100 card-img-top bd-placeholder-img" width="100%" height="256" role="img" src="{{ image.Board_image.url }}">
                                            </a>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                            <div class="card-body">
                                <p class="card-title h4" href="{% url 'articleapp:DetailPost' post.Board_id %}">{{ post.Board_title|truncatechars:9 }}</p>
                                <div class="btn-group align-middle">
                                    공구&nbsp;
                                    {% if post.Board_share == '희망' %}
                                    <i class="bi bi-check-square-fill"style='font-size:1.1rem;color:green;padding-top:0.2rem;'></i>
                                    {% else %}
                                    <i class="bi bi-x-square-fill" style='font-size:1.1rem;color:red;padding-top:0.2rem;'></i>
                                    {% endif %}
                                </div>
                                <div>
                                    {% if '그립톡' in post.Board_gtype %}
                                    <span class="custom-control custom-switch badge">
                                        그립톡
                                    </span>
                                    {% endif %}
                                    {% if '키링' in post.Board_gtype %}
                                    <span class="custom-control custom-switch badge">
                                        키링
                                    </span>
                                    {% endif %}
                                    {% if '티셔츠' in post.Board_gtype %}
                                    <span class="custom-control custom-switch badge">
                                        티셔츠
                                    </span>
                                    {% endif %}
                                    {% if '핸드폰케이스' in post.Board_gtype %}
                                    <span class="custom-control custom-switch badge">
                                        핸드폰케이스
                                    </span>
                                    {% endif %}
                                </div>
                                <div class="d-flex justify-content-between align-items-center mt-2">
                                    <small class="text-muted">{{ post.Board_writer.nickname }}</small>
                                    <small class="text-muted">{{ post.Board_datetime|date:'Y-m-d' }}</small>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <h5 style="text-align: center; font-size: 30px; padding-top: 50px; width: 1000px;">작성된 게시글이 없습니다.</h5>
        {% endif %}
    </div>
</div>
{% endblock %}

BP/profiles/templates/profiles/update.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/accounts.css' %}">
<link rel="stylesheet" href="{% static 'css/main/style_mydesign.css' %}">
<div class="row flex-nowrap">
    <div class="col-6 bd-sidebar">
        <div class="bd-sidebar-body">
            <ul class="nav">
                <li><a href="/profiles/mydesign" class="btn btn-lg mt-5" role="button">나의 디자인</a></li>
                <li><a href="{% url 'accountsapp:detail' user.pk %}" class="btn btn-lg mt-5" role="button">개인 정보 수정</a></li>
            </ul>
        </div>
    </div>
    <div class="profile">
        <h1 class="title">프로필 변경</h1>
        <form action="{% url 'profilesapp:update' user.profile.pk %}" class="profile-update" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="profile-img">
                <img id="preview" src="{{ user.profile.image.url }}" alt="default-img">
                {{ form.image }}
            </div>
            <div class="user-detail">
                <div class="user-introduce">
                    {{ form.message }}
                </div>
                <button class="btn btn-success">
                    수정하기
                </button>
            </div>
        </form>
    </div>
</div>
<script>
    function setThumbnail(event) {
      var reader = new FileReader();
      reader.onload = function(event) {
        var img = document.getElementById("preview");
        console.log(event.target.result);
        img.src=event.target.result;
      };

      reader.readAsDataURL(event.target.files[0]);
    }
  </script>
{% endblock %}