BP/BP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls')),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('profiles/', include('profiles.urls')),
    path('imageconvert/', include('imageconvert.urls', namespace='imageconvert')),
    path('goods/', include('goods.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BP/accounts/urls.py
from django.urls import path
from django.urls import path, include
# from .views import home_screen_view
from accounts.views import signup, login, logout, detail, update, password_change, delete

app_name = 'accountsapp'

urlpatterns = [
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('detail/<int:pk>/', detail, name='detail'),
    path('update/<int:pk>/', update, name='update'),
    path('delete/', delete, name='delete'),
    path('password/<int:pk>', password_change, name='password'),
]

BP/profiles/urls.py
from django.urls import path
from profiles.views import update, mydesign

app_name = 'profilesapp'

urlpatterns = [
    path('update/<int:pk>/', update, name='update'),
    path('mydesign/', mydesign, name='mydesign'),
]

BP/accounts/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db import models
 
class MyAccountManager(BaseUserManager):
    # 일반 user 생성, username 이 userID를 의미함
    def create_user(self, username, name, nickname, email, password=None):
        if not username:
            raise ValueError("Users must have an userID.")
        if not name:
            raise ValueError("Users must have a name.")
        if not nickname:
            raise ValueError('Users must have a nickname.')
        if not email:
            raise ValueError("Users must have an email address.")


        user = self.model(
            username = username,
            name = name,
            nickname = nickname,            
            email = self.normalize_email(email),
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
 
    # 관리자 User 생성
    def create_superuser(self, username, name, nickname, email, password):
        user = self.create_user(
            username = username,
            name = name,
            nickname = nickname,            
            email = self.normalize_email(email),
            password=password
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user
 
class Account(AbstractBaseUser):
    username    = models.CharField(max_length=30, unique=True)
    name        = models.CharField(max_length=40, null=False, blank=False)    
    nickname    = models.CharField(max_length=30, unique=False)
    email       = models.EmailField(verbose_name='email', max_length=60, unique=True)
    create_at   = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login  = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin    = models.BooleanField(default=False)
    is_active   = models.BooleanField(default=True)
    is_staff    = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
 
    objects = MyAccountManager()  # 헬퍼 클래스 사용
 
    USERNAME_FIELD = 'username'  # 로그인 ID로 사용할 필드
    REQUIRED_FIELDS = ['name', 'nickname', 'email'] # 필수 작성 필드
 
    def __str__(self):
        return self.username
    
    def has_perm(self, perm, obj=None):
        return self.is_admin
 
    def has_module_perms(self, app_lable):
        return True

BP/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth import authenticate, get_user_model
from accounts.models import Account
from django.contrib.auth.hashers import check_password

# 회원 가입 폼
class SignupForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Add a valid email address.')
    
    class Meta:
        model = Account
        fields = ('username', 'name', 'nickname', 'email', 'password1', 'password2', )
        widgets = {
            'username': forms.TextInput(attrs={
                'readonly': True,
                'style': 'display: none;'})
        }
 
    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            account = Account.objects.get(username=username)
        except Exception as e:
            return username
        raise forms.ValidationError(f"이미 사용중인 이름입니다.")
    
    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        try:
            account = Account.objects.get(email=email)
        except Exception as e:
            return email
        raise forms.ValidationError(f"이미 사용중인 이메일입니다.")
    
    def clean_nickname(self):
        nickname = self.cleaned_data['nickname'].lower()
        try:
            account = Account.objects.get(nickname=nickname)
        except Exception as e:
            return nickname
        raise forms.ValidationError(f"이미 사용중인 별명입니다.")
  
 
 
 
# 로그인 인증 폼
class AccountAuthForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
 
    class Meta:
        model = Account
        fields = ('username', 'password')
 
    def clean(self):
        if self.is_valid():
            username = self.cleaned_data['username']
            password = self.cleaned_data['password']
            if not authenticate(username=username, password=password):
                raise forms.ValidationError("로그인이 실패했습니다.")


# 회원정보 수정 폼
class CustomUserChangeForm(UserChangeForm):
    
    class Meta:
        model = get_user_model()
        fields = ['username', 'name', 'nickname', 'email']
        widgets = {
            'username': forms.TextInput(attrs={
                'class': 'disabled',
                'readonly': True
            }),
            'name': forms.TextInput(attrs={
                'class': 'disabled',
                'readonly': True
            }),
        }
        
# 비빌번호 변경 폼
class CustomPasswordChangeForm(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super(CustomPasswordChangeForm, self).__init__(*args, **kwargs)
        self.fields['old_password'].label = '기존 비밀번호'
        self.fields['old_password'].widget.attrs.update({
            'class': 'form-control',
            'autofocus': False,
        })
        self.fields['new_password1'].label = '새 비밀번호'
        self.fields['new_password1'].widget.attrs.update({
            'class': 'form-control',
        })
        self.fields['new_password2'].label = '새 비밀번호 확인'
        self.fields['new_password2'].widget.attrs.update({
            'class': 'form-control',
        })
        
        
# 회원탈퇴 비밀번호 확인 폼
class CheckPasswordForm(forms.Form):
    password = forms.CharField(label='비밀번호', widget=forms.PasswordInput(
        attrs={'class': 'form-control',}), 
    )
    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.user = user

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        confirm_password = self.user.password
        
        if password:
            if not check_password(password, confirm_password):
                self.add_error('password', '비밀번호가 일치하지 않습니다.')

BP/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import login as auth_login, logout as auth_logout, authenticate, update_session_auth_hash
from accounts.forms import SignupForm, AccountAuthForm, CustomUserChangeForm, CustomPasswordChangeForm, CheckPasswordForm
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib import messages
 
 
def signup(request, *args, **kwargs):
    user = request.user
    if user.is_authenticated:
        return redirect("mainapp:main")
 
    context = {}
    if request.POST:
        form = SignupForm(request.POST)
        print(form)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username').lower()
            raw_password = form.cleaned_data.get('password1')
            account = authenticate(username=username, password=raw_password)
            auth_login(request, account)
            destination = get_redirect_if_exists(request)
            if destination:
                return redirect(destination)
            return redirect("mainapp:main")
        else:
            context['registration_form'] = form
    else:
        form = SignupForm()
        context['registration_form'] = form
 
    return render(request, 'accounts/signup.html', context)
 
 
def logout(request):
    auth_logout(request)
    return redirect("/")
 
 
def login(request, *args, **kwargs):
    context = {}
 
    user = request.user
    if user.is_authenticated:
        return redirect("mainapp:main")
 
    destination = get_redirect_if_exists(request)
    if request.POST:
        form = AccountAuthForm(request.POST)
        if form.is_valid():
            print('??')
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(username=username, password=password)
            if user:
                auth_login(request, user)
                if destination:
                    return redirect(destination)
                return redirect("mainapp:main")
    else:
        form = AccountAuthForm()
    print('111')
    context['login_form'] = form
 
    return render(request, "accounts/login.html", context)
 
 
def get_redirect_if_exists(request):
    redirect = None
    if request.GET:
        if request.GET.get("next"):
            redirect = str(request.GET.get("next"))
    return redirect

def detail(request, pk):
    User = get_user_model()
    user = get_object_or_404(User, pk=pk)
    context = {
        'user': user
    }
    return render(request, 'accounts/detail.html', context)

@login_required
def update(request, pk):
    print('11')
    if request.method == 'POST':
        print('33')
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            print('as')
            form.save()
            return redirect('accountsapp:detail', pk)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form
    }
    print('22')
    return render(request, 'accounts/update.html', context)


@login_required
def delete(request):
    if request.method == 'POST':
        form = CheckPasswordForm(request.user, request.POST)
        
        if form.is_valid():
            request.user.delete()
            messages.success(request, "회원탈퇴가 완료되었습니다.")
            auth_logout(request)
            return redirect("mainapp:main")
    else:
        form = CheckPasswordForm(request.user)

    return render(request, 'accounts/delete.html', {'form': form})




def password_change(request, pk):
    if request.method == 'POST':
        password_change_form = CustomPasswordChangeForm(request.user, request.POST)
        if password_change_form.is_valid():
            user = password_change_form.save()
            update_session_auth_hash(request, user)
            messages.success(request, "비밀번호를 성공적으로 변경하였습니다.")
            return redirect('accountsapp:detail', pk)
    else:
        password_change_form = CustomPasswordChangeForm(request.user)

    return render(request, 'accounts/password.html', {'password_change_form':password_change_form})

BP/accounts/templates/accounts/delete.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/accounts.css' %}">
<link rel="stylesheet" href="{% static 'css/checkbox.css' %}"> 
<link rel="stylesheet" href="{% static 'css/main/style_mydesign.css' %}">
<div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-6 bd-sidebar">
            <div class="bd-sidebar-body">
                <ul class="nav">
                    <li><a href="/profiles/mydesign" class="btn btn-lg mt-5" role="button">나의 디자인</a></li>
                    <li><a href="{% url 'accountsapp:detail' user.pk %}" class="btn btn-lg mt-5" role="button">개인 정보 수정</a></li>
                </ul>
            </div>
        </div>
        <div class="profile">
            <h2 style="margin: 20px;">회원탈퇴</h2>
            <div class="card-body">
                <form method="POST" novalidate>
                    {% csrf_token %}
                    <p class="fs-5 my-3">인생굿즈에서 <strong>{{ user.name }}</strong> 회원님의 계정이 삭제됩니다.<br>탈퇴시 개인정보 및 이용정보가 삭제되며 복구할 수 없습니다. <br>본인의 비밀번호를 입력한 후 하단의 유의사항 동의에 체크하세요.</p>
                    <div class="my-2 md-form">
                        <label name="label_password" for="{{ password_form.password.id_for_label }}"><i
                                class="fas fa-lock"></i>&nbsp;&nbsp;{{ form.password.label }}</label>
                        {{ form.password }}
                        {% if form.password.errors %}
                        <script type="text/javascript">
                            document.getElementsByName('password')[0].setAttribute('class',
                                'form-control is-invalid')
                        </script>
                        {% for error in form.password.errors %}
                        <div class="invalid-feedback" style="margin: 0px 0px -2px 4px">
                            {{ error }}
                        </div>
                        {% endfor %}
                        {% endif %}
                        <small style="margin-left: 4px; margin-top:8px; margin-bottom: 30px;" class="form-text text-muted">
                            본인인증을 위해 비밀번호를 입력해주세요.
                        </small>
                    </div>

                    <label>
                        <input type="checkbox" name="ck" onClick="checkDisable(this.form)">
                        <span style="color:#d14040f2; font-weight: bold;">유의사항 동의</span>
                    </label>
                    <div style="text-align: center; margin: 10px 0px;">
                        <p style="color:gray; margin-bottom: 10px;">{{ user.name }} 계정이 삭제됩니다.</p>
                        <a href="{% url 'accountsapp:detail' user.pk %}" class="btn btn-secondary" id="back_btn">돌아가기</a>
                        <button type="submit" class="btn btn-danger" name="bt" id="detail_btn" disabled="true">탈퇴하기</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">
    function checkDisable(form) {
        if (form.ck.checked == true) {
            form.bt.disabled = false;
        } else {
            form.bt.disabled = true;
        }
    }
</script>
{% endblock %}

BP/accounts/templates/accounts/detail.html
{% extends 'base.html' %}
{% load static %}
{% block content%}
<link rel="stylesheet" href="{% static 'css/accounts.css' %}">
<link rel="stylesheet" href="{% static 'css/main/style_mydesign.css' %}">
<div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="bd-sidebar">
            <div class="bd-sidebar-body">
                <ul class="nav">
                    <li><a href="/profiles/mydesign" class="btn btn-lg mt-5" role="button">나의 디자인</a></li>
                    <li><a href="{% url 'accountsapp:detail' user.pk %}" class="btn btn-lg mt-5" role="button">개인 정보 수정</a></li>
                </ul>
            </div>
        </div>
        <div class="profile">
            <h1 class="title">프로필</h1>
            <div class="user">
                <div class="user-image">
                    <img src="{{ user.profile.image.url }}" alt="">
                </div>
                <div class="user-detail">
                    <div class="user-name">
                        <h2>{{ user.username }}</h2>
                    </div>
                    <div class="user-introduce">
                        {{ user.profile.message }}
                    </div>
                    {% if request.user.pk == user.pk %}
                    <button class="btn btn-secondary">
                        <a href="{% url 'profilesapp:update' user.profile.pk %}">프로필 변경</a>
                    </button>
                    {% endif %}
                </div>
            </div>
            {% if request.user.pk == user.pk %}
            <div class="account">
                <h1 class="title">개인정보</h1>
                <div class="nickname tap">
                    <div class="name">닉네임</div>
                    <div>{{ user.nickname }}</div>
                </div>
                <div class="email tap">
                    <div class="name">이메일</div>
                    <div>{{ user.email }}</div>
                </div>
                <div class="buttons">
                    <button class="btn btn-success">
                        <a href="{% url 'accountsapp:update' user.pk %}">개인정보 변경</a>
                    </button>
                    <button class="btn btn-danger">
                        <a href="{% url 'accountsapp:delete' %}">탈퇴하기</a>
                    </button>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

BP/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/accounts.css' %}">
<div class="content">
    <div class="container">
        <div class="forms">
            <div class="form login">
                <span class="title">Login</span>
                <form action="{% url 'accountsapp:login' %}" method="post">
                    {% csrf_token %}
                    <div class="input-field">
                        <input type="text" name="username" placeholder="아이디" required>
                        <i class="uil uil-user icon"></i>
                    </div>
                    <div class="input-field">
                        <input type="password" name="password" id="inputPassword" class="password" placeholder="비밀번호" required>
                        <i class="uil uil-lock icon"></i>
                    </div>
                    <div class="input-field button">
                        <input type="submit" value="로그인">
                    </div>
                    {% for field in login_form %}
                    <p>
                        {% for error in field.errors %}
                            <p style="color: red">{{ error }}</p>
                        {% endfor %}
                    </p>
                    {% endfor %}
                    {% if login_form.non_field_errors %}
                        <div style="color: red">
                            <p>{{ login_form.non_field_errors }}</p>
                        </div>
        
                    {% endif %}
                </form>

                <div class="login-signup">
                    <span class="text">Not a member?
                        <a href="{% url 'accountsapp:signup' %}" class="text signup-link">Signup Now</a>
                    </span>
                </div>
            </div>
        </div>
        {% include 'accounts/social_login.html' %}
    </div>
</div>

<script src="{% static 'js/accounts.js'%}"></script>
{% endblock %}

BP/accounts/templates/accounts/password.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/accounts.css' %}">
<link rel="stylesheet" href="{% static 'css/main/style_mydesign.css' %}">
<div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-6 bd-sidebar">
            <div class="bd-sidebar-body">
                <ul class="nav">
                    <li><a href="/profiles/mydesign" class="btn btn-lg mt-5" role="button">나의 디자인</a></li>
                    <li><a href="{% url 'accountsapp:detail' user.pk %}" class="btn btn-lg mt-5" role="button">개인 정보 수정</a></li>
                </ul>
            </div>
        </div>
        <div class="profile">
            <div class="card-header">
                <h1>비밀번호 변경</h1>
            </div>
            <div class="card-body">
                <form method="POST" novalidate>
                    {% csrf_token %}
                    <div class="mb-4 md-form">
                        <label name="label_old_password" for="{{ password_change_form.old_password.id_for_label }}"><i
                                class="fas fa-lock"></i>&nbsp;&nbsp;{{ password_change_form.old_password.label }}</label>
                        {{ password_change_form.old_password }}
                        <script type="text/javascript">
                            if (document.getElementsByName('old_password')[0].value != '') {
                                document.getElementsByName('label_old_password')[0].setAttribute('class',
                                    'active');
                            }
                        </script>
                        {% if password_change_form.old_password.errors %}
                        <script type="text/javascript">
                            document.getElementsByName('old_password')[0].setAttribute('class',
                                'form-control is-invalid')
                        </script>
                        {% for error in password_change_form.old_password.errors %}
                        <div class="invalid-feedback" style="margin-bottom:-10px;">
                            {{ error }}
                        </div>
                        {% endfor %}
                        {% endif %}
                    </div>
                    <!--새 비밀번호-->
                    <div class="mb-4 md-form">
                        <label name="label_new_password1" for="{{ password_change_form.new_password1.id_for_label }}"><i
                                class="fas fa-unlock"></i>&nbsp;&nbsp;{{ password_change_form.new_password1.label }}</label>
                        {{ password_change_form.new_password1 }}
                        <script type="text/javascript">
                            if (document.getElementsByName('new_password1')[0].value != '') {
                                document.getElementsByName('label_new_password1')[0].setAttribute('class',
                                    'active');
                            }
                        </script>
                        {% if password_change_form.new_password1.errors %}
                        <script type="text/javascript">
                            document.getElementsByName('new_password1')[0].setAttribute('class',
                                'form-control is-invalid')
                        </script>
                        {% for error in password_change_form.new_password1.errors %}
                        <div class="invalid-feedback" style="margin-bottom:-10px;">
                            {{ error }}
                        </div>
                        {% endfor %}
                        {% endif %}
                    </div>
                    <!--새 비밀번호확인-->
                    <div class="mb-4 md-form">
                        <label name="label_new_password2" for="{{ password_change_form.new_password2.id_for_label }}"><i
                                class="fas fa-unlock-alt"></i>&nbsp;&nbsp;{{ password_change_form.new_password2.label }}</label>
                        {{ password_change_form.new_password2 }}
                        <script type="text/javascript">
                            if (document.getElementsByName('new_password2')[0].value != '') {
                                document.getElementsByName('label_new_password2')[0].setAttribute('class',
                                    'active');
                            }
                        </script>
                        {% if password_change_form.new_password2.errors %}
                        <script type="text/javascript">
                            document.getElementsByName('new_password2')[0].setAttribute('class',
                                'form-control is-invalid')
                        </script>
                        {% for error in password_change_form.new_password2.errors %}
                        <div style="white-space: nowrap;" class="invalid-feedback">
                            {{ error }}
                        </div>
                        {% endfor %}
                        {% endif %}
                        <small style="margin-left: 4px; margin-top:8px; margin-bottom: 30px;" class="form-text text-muted">
                            최소 8개의 숫자와 문자 또는 특수기호를 입력해주세요.
                        </small>
                    </div>
                    <div style="text-align: center; margin: 40px;">
                        <a href="{% url 'accountsapp:detail' user.pk %}" class="btn btn-warning" id="back_btn">돌아가기</a>
                        <button type="submit" class="btn btn-success" id="detail_btn">변경하기</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

BP/accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.0/css/line.css">
<link rel="stylesheet" href="{% static 'css/accounts.css' %}">
<div class="content">
    <div class="container active">
        <div class="forms">
            <div class="form signup">
                <span class="title">Sign up</span>

                <form  method="post">
                    {% csrf_token %}
                    <div class="input-field">
                        <input type="text" name="username" id="username" placeholder="아이디" required>
                        <i class="uil uil-user"></i>
                    </div>
                    <div class="input-field">
                        <input type="text" name="name" id="name" placeholder="이름" required>
                        <i class="uil uil-smile"></i>
                    </div>
                    <div class="input-field">
                        <input type="text" name="nickname" id="nickname"  placeholder="닉네임" required>
                        <i class="uil uil-laughing"></i>
                        <!-- <button class="duplicate-check">중복확인</button> -->
                    </div>
                    <div class="input-field">
                        <input type="email" name="email" id="inputEmail"  placeholder="이메일" required>
                        <i class="uil uil-envelope icon"></i>
                    </div>
                    <div class="input-field">
                        <input type="password" name="password1" class="password" placeholder="비밀번호" required>
                        <i class="uil uil-lock icon"></i>
                    </div>
                    <div class="input-field">
                        <input type="password" name="password2" class="password" placeholder="비밀번호 확인" required>
                        <i class="uil uil-lock icon"></i>
                    </div>

                    <div class="checkbox-text">
                        <div class="checkbox-content">
                            <input type="checkbox" id="termCon">
                            <label for="termCon" class="text">회원가입 동의</label>
                        </div>
                    </div>

                    <div class="input-field button">
                        <input type="submit" value="회원가입">
                    </div>
                </form>

                <div class="login-signup">
                    <span class="text">Already a member?
                        <a href="{% url 'accountsapp:login' %}" class="text login-link">Login Now</a>
                    </span>
                </div>
                {% for field in registration_form %}
                    <p>
                        {% for error in field.errors %}
                            <p style="color: red">{{ error }}</p>
                        {% endfor %}
                    </p>
                {% endfor %}
                {% if registration_form.non_field_errors %}
                    <div style="color: red">
                        <p>{{ registration_form.non_field_errors }}</p>
                    </div>
    
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

BP/accounts/templates/accounts/social_login.html
{% load static %}

{% static 'img/social/btnG.png' as naver_button %}
{% static 'img/social/btnW.png' as naver_button_hover %}
{% static 'img/social/kakao.png' as kakao_button %}
{% static 'img/social/kakaoh.png' as kakao_button_hover %}

{% load i18n %}
{% load account socialaccount %}
{% get_providers as socialaccount_providers %}
<div class="social">
    <h4>소셜로그인</h4>
    <div class="d-flex mb-4 justify-content-around">
        {% for provider in socialaccount_providers %}
            {% if provider.name == "Naver" %}
                <div class="button">
                    <a href="{% provider_login_url provider.id process=process scope=scope auth_params=auth_params %}">
                        <img src="{{ naver_button }}" height="40">
                </div>
            {% elif provider.name == "Kakao" %}
                <div class="button">
                    <a href="{% provider_login_url 'kakao' method='oauth2' %}">
                        <img src="{{ kakao_button }}" height="40">
                </div>
            {% endif %}
        {% endfor %}
    </div>
</div>

BP/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load static %}
{% block content %} 
<link rel="stylesheet" href="{% static 'css/accounts.css' %}">
<link rel="stylesheet" href="{% static 'css/main/style_mydesign.css' %}">
<div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-6 bd-sidebar">
            <div class="bd-sidebar-body">
                <ul class="nav">
                    <li><a href="/profiles/mydesign" class="btn btn-lg mt-5" role="button">나의 디자인</a></li>
                    <li><a href="{% url 'accountsapp:detail' user.pk %}" class="btn btn-lg mt-5" role="button">개인 정보 수정</a></li>
                </ul>
            </div>
        </div>
        <div class="profile">
            <h1 class="title">개인정보</h1>
            <form action="{% url 'accountsapp:update' user.pk %}" method="POST" class="account-update">
                {% csrf_token %}
                <label for="id_username">아이디</label>
                {{ form.username }}
                <label for="id_name">이름</label>
                {{ form.name }}
                <label for="id_nickname">닉네임</label>
                {{ form.nickname }}
                <label for="id_email">이메일</label>
                {{ form.email }}
                <div class="button-group">
                    <a href="{% url 'accountsapp:password' user.pk %}" class="btn btn-danger" role="button">비밀번호 변경</a>
                    <button class="btn btn-success">수정하기</button>
                    <a href="{% url 'accountsapp:detail' user.pk %}" class="btn btn-secondary">돌아가기</a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}