BP/BP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('article/', include('article.urls')),
    path('', include('main.urls')),
    path('accounts/', include('accounts.urls')),
    path('profiles/', include('profiles.urls')),
    path('imageconvert/', include('imageconvert.urls', namespace='imageconvert')),
    path('goods/', include('goods.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BP/article/urls.py
from django.urls import path

from . import views

app_name = 'articleapp'

urlpatterns = [
    path('create/', views.CreatePost, name='CreatePost'),
    path('detail/<int:postid>', views.DetailPost, name='DetailPost'),
    path('delete/<int:postid>', views.DeletePost, name='DeletePost'),
    path('update/<int:postid>', views.UpdatePost, name='UpdatePost'),
    path('createcomment/<int:postid>', views.CreateComment, name='CreateComment'),
    path('updatecomment/', views.UpdateComment, name='UpdateComment'),
    path('deletecomment/<int:postid>/<int:commentid>', views.DeleteComment, name='DeleteComment'),
    path('', views.ListPost, name='ListPost'),
]

BP/article/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.conf import settings
from django.urls import reverse
import os
# Create your models here.

share_choice = [
    ('희망', '희망'),
    ('비희망', '비희망'), 
]

def user_directory_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = filename.split('.')[0]
    now = datetime.datetime.now()
    filename = filename + now.strftime('%Y%m%d%H%M%S')
    filepath = 'article/image/'
    return filepath + filename + '.' + ext

class Post(models.Model):
    Board_id = models.AutoField(primary_key = True)
    Board_share = models.CharField(max_length=100, choices=share_choice, default='희망')
    Board_gtype = models.CharField(max_length=100)
    Board_title = models.CharField(max_length=250)
    Board_content = models.TextField()
    Board_datetime = models.DateTimeField(default=timezone.now)
    Board_writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)

class PostImage(models.Model):
    Post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='postimage')
    Board_image = models.ImageField(upload_to=user_directory_path)
    
class Comment(models.Model):
    Comment_post = models.ForeignKey(Post, on_delete=models.CASCADE, null=True)
    Comment_content = models.CharField(max_length=200)
    Comment_writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    Comment_datetime = models.DateTimeField(auto_now=True)

BP/article/forms.py
from django import forms
from .models import Post, PostImage, Comment

goods_type = [
    ('그립톡', '그립톡'), 
    ('키링', '키링'),
    ('티셔츠', '티셔츠'),
    ('핸드폰케이스', '핸드폰케이스'),
     ('해당없음', '해당없음'),
]
class PostForm(forms.ModelForm):
    Board_gtype = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple(),
        choices=goods_type,
        error_messages={'required':'굿즈 종류를 선택해주세요.'},
        required=True,
    )
    
    class Meta:
        model = Post
        fields = ['Board_share', 'Board_gtype', 'Board_title', 'Board_content']
        widgets = {
            'Board_share' : forms.RadioSelect(),
            'Board_title' : forms.TextInput(attrs={
                'class':'form-control',
                'placeholder':"제목을 입력해주세요.",
                'style':'border: none;'
            }),
            'Board_content' : forms.Textarea(attrs={
                'class':'form-control',
                'rows':'10',
                'placeholder':"내용을 입력해주세요.",
                'style':'height: 300px; border: none; resize: none;'
            }),
        }
    

        
class Post_ImageForm(forms.ModelForm):
    Board_image = forms.ImageField(
            label='image',
            widget=forms.ClearableFileInput(
                attrs={
                    'onchange':"addFile(this)",
                    'multiple': True,
                }
            )
        )
    
    class Meta:
        model = PostImage
        fields = ['Board_image',]

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['Comment_content',]
        widgets = {
            'Comment_content' : forms.Textarea(attrs={
                'placeholder':"댓글을 입력해주세요.",
                'style':'width: 100%; height:10%; resize: none;border-radius: 0.25rem;border: 1px solid #ced4da;',
            }),
        }
        
        

BP/article/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PostForm, Post_ImageForm, CommentForm
from .models import Post, PostImage, Comment
from accounts.models import Account
import logging
import datetime
from django.contrib.auth.decorators import login_required
import json
from django.http import JsonResponse, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Q
logger = logging.getLogger('mylogger')

@login_required
def CreatePost(request):
    logger.error(request.user)
    if request.method == 'POST' and request.FILES['Board_image']:
        post_form = PostForm(request.POST)
        post_imageform = Post_ImageForm(request.POST, request.FILES)
        # image = request.FILES['Board_image']
        images = request.FILES.getlist('Board_image')
        if post_form.is_valid():
            user_id = request.user
            user = Account.objects.get(username = user_id)
            result = ''
            for i in request.POST.getlist('Board_gtype'):
                result += i
                result += ' '
            p_form = Post(
                Board_share = post_form.cleaned_data['Board_share'],
                Board_gtype = result,
                Board_title = post_form.cleaned_data['Board_title'],
                Board_content = post_form.cleaned_data['Board_content'],
                Board_writer = user,
            )
            p_form.save()
            post = p_form
            for image in images:
                PostImage.objects.create(
                    Post = post,
                    Board_image = image
                )    
            return redirect('articleapp:DetailPost',  post.Board_id)
    else:
        post_form = PostForm()
        post_imageform = Post_ImageForm()
    return render(request, 'Create_Post.html',  {'post_form': post_form, 'post_imageform' : post_imageform})

@login_required
def DetailPost(request, postid):
    post = get_object_or_404(Post, Board_id=postid)
    comment = CommentForm()
    return render(request, 'Detail_Post.html', {'post':post, 'comment':comment})

@login_required 
def DeletePost(request, postid):
    post = get_object_or_404(Post, Board_id=postid)
    post.delete()
    return redirect('mainapp:main')

@login_required
def UpdatePost(request, postid):
    post = get_object_or_404(Post, Board_id=postid)
    
    if request.method == 'POST' and request.FILES['Board_image']:
        post_form = PostForm(request.POST)
        post_imageform = Post_ImageForm(request.POST, request.FILES)
        if request.POST.getlist('Board_gtype'):
            post.postimage.all().delete()
            post.Board_share=request.POST['Board_share']
            result = ''
            for i in request.POST.getlist('Board_gtype'):
                result += i
                result += ' '
            # logger.error(result)
            post.Board_gtype=result
            # post.Board_gtype=request.POST.getlist('Board_gtype')
            post.Board_title=request.POST['Board_title']
            post.Board_content=request.POST['Board_content']
            post.Board_datetime=datetime.datetime.now()
            post.save()
            images = request.FILES.getlist('Board_image')
            for image in images:
                PostImage.objects.create(
                    Post = post,
                    Board_image = image            
                )
            return redirect('/article/detail/'+str(postid))
        else:
            return render(request, 'Update_Post.html', {'post_form': post_form, 'post_imageform' : post_imageform, 'postid':postid})
    else:
        #logger.error( Post.objects.get(Board_id=postid).Board_gtype.split(' '))
        # #post_form = PostForm(initial={'Board_share':post.Board_share, 'Board_gtype': Post.objects.filter(Board_id=postid).values_list('Board_gtype', flat=True),
        #                               })
        post_form = PostForm(instance=post, initial={'Board_gtype': Post.objects.get(Board_id=postid).Board_gtype.split(' ')})
        post_imageform = Post_ImageForm()
        context = {'post_form': post_form, 
                   'post_imageform' : post_imageform, 
                   'postid':postid}
        return render(request, 'Update_Post.html',  context)

@login_required
def CreateComment(request, postid):
    c_form = CommentForm(request.POST)
    if c_form.is_valid():
        user_id = request.user
        user = Account.objects.get(username = user_id)
        post = get_object_or_404(Post, Board_id = postid)
        f_c_form = Comment(
            Comment_post = post,
            Comment_content = c_form.cleaned_data['Comment_content'],
            Comment_writer = user,
        )
        f_c_form.save()
    return redirect('articleapp:DetailPost', postid)

@login_required
@csrf_exempt
def UpdateComment(request):
    data = json.loads(request.body.decode('utf8'))
    comment = Comment.objects.filter(id=data.get('id'))
    context = {
        'result' : 'no',
    }
    if comment is not None:
        comment.update(Comment_content=data.get('Comment_content'), Comment_datetime=datetime.datetime.now())
        context = {
            'result':'ok',
        }
        return JsonResponse(context)
    return JsonResponse(context)
    
@login_required
def DeleteComment(request, postid, commentid):
    comment = get_object_or_404(Comment, pk=commentid)
    comment.delete()
    return redirect('articleapp:DetailPost', postid)

def ListPost(request):
    postlist = Post.objects.all().order_by('-Board_id')
    if 'search_type' in request.GET:
        result = []
        type = request.GET['search_type']
        search  = request.GET['searched']

        if 'search_share' in request.GET:
            share = request.GET['search_share']
            postlist = postlist.filter(Q(Board_share=share)).distinct()
            
        if 'search_gtype' in request.GET: # 두 가지 선택되면 두 가지 동시선택된 게시물만..
            gtype = request.GET.getlist('search_gtype')
            for i in gtype:
                postlist = postlist.filter(Q(Board_gtype__icontains = i)).distinct()
        
            
        if request.GET['searched'] != '':
            kewards = search.split(' ')
            if type == 's_total':
                for kw in kewards:
                    result += postlist.filter(Q(Board_title__icontains=kw) | 
                                            Q(Board_content__icontains=kw)| 
                                            Q(Board_writer__nickname__icontains=kw)).distinct()
            elif type == 's_title':
                for kw in kewards:
                    result += postlist.filter(Q(Board_title__icontains=kw)).distinct()
            elif type == 's_content':
                for kw in kewards:
                    result += postlist.filter(Q(Board_content__icontains=kw)).distinct()
            else:
                for kw in kewards:
                    result += postlist.filter(Q(Board_writer__nickname__icontains=kw)).distinct()
        else:
            result = postlist
        
        context = {
            'postlist':result,
            'search':search,
        }
    else:
        context = {'postlist':postlist}
    return render(request, 'List_Post.html', context)

BP/article/templates/Create_Post.html
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<script src="{% static 'js/article.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/article.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"/>
<form class='form-control' method='post' enctype="multipart/form-data">
    {% csrf_token %}
    <div style='margin-top: 1rem!important'>
        <h3>공유 게시판</h3>
    </div>
    <div class='b_info'>
        <hr />
        <span>공유 게시판 > 글 작성</span>
        <hr />
    </div>
    <span style='font-size: 1.15rem;float:right;color:#848897;'><mark class="red">*</mark>표시는 필수 입력 항목입니다.</span>
    <div class='table-responsive'>
        <table class='create_table'>
            <tr>
                <td class='thst' height=36px;><mark class="red">*</mark>공구여부</td>
                <td class='tdst'>{{ post_form.Board_share }}</td>
            </tr>
            <tr>
                <td rowspan="2" class='thst' height=36px;><mark class="red">*</mark>굿즈종류</td>
                <td class='tdst'>{{ post_form.Board_gtype}}</td>
            </tr>
            <tr>
                <td class='tdst'>
                {% if post_form.Board_gtype.errors %}
                    <span style="color:red;}">{{post_form.Board_gtype.errors}}</span>
                {% endif %}</td>
            </tr>
            <tr>
                <td class='thst' height=36px;><mark class="red">*</mark>제목</td>
                <td class='tdst'>{{ post_form.Board_title }}</td>
            </tr>
            <tr>
                <td class='thst'><mark class="red">*</mark>내용</td>
                <td class='tdst'>{{ post_form.Board_content }}</td>
            </tr>
            <tr id = 'image'>
                <td class='thst' style='border-bottom:none;' rowspan='2'><mark class="red">*</mark>이미지 첨부</td>
            </tr>
            <tr>
                <td class='insert'>
                    {{ post_imageform.Board_image }}<div class="file-list"></div></td>
            </tr>
        </table>
    </div>
    <div style='text-align:center'><input class="btn btn-secondary" onClick = "location.href='{% url 'articleapp:ListPost' %}'" type='button' value='취소'>&nbsp&nbsp<input class="btn btn-primary" type='submit' value='등록'></div>
</form>
{% endblock %}

BP/article/templates/Detail_Post.html
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="https://code.iconify.design/iconify-icon/1.0.2/iconify-icon.min.js"></script>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/article.css' %}">
<script src="{% static 'js/article.js' %}"></script>
<div class='detail_body'>
    <div style='margin-top: 1rem!important'>
        <h3>공유 게시판</h3>
    </div>
    <div class='b_info'>
        <hr />
        <span>공유 게시판 > 게시글</span>
        <hr />
    </div>
    <div class="thumbnail" >
        {% for image in post.postimage.all %}
            {% if forloop.counter == 1%}
                <div id="mainImg"><img src ="{{ image.Board_image.url }}" alt="image"></div><div class="thumbs">
            {% endif %}
            <a href="" alt="image{{ forloop.counter }}"><img src ="{{ image.Board_image.url }}"></a>
        {% endfor %}
        </div>
    </div>
    <div class='detail'>
        <div style='height:6%;margin-bottom:2%;'>
            {% if request.user == post.Board_writer%}
            <input style='float:right;' type='button' class="btn btn-primary" onclick='p_udt({{ post.Board_id }});' value='수정'>
            <input style='float:right;margin-right:8px;' type='button' class="btn btn-secondary" onclick='p_del({{ post.Board_id }});' value='삭제'>
            {% endif %}
        </div>
        <div>
        <table class='detail_table'>
            <tr>
                <td class='detail_td1' style='border-radius: 10px 0 0 0;'>공구 여부</td>
                <td class='detail_td2'>{{post.Board_share}}</td>
                <td class='detail_td1'>작성자</td>
                <td class='detail_td2'style='border-radius: 0 10px 0 0 ;'>{{post.Board_writer.nickname}}</td>
            </tr>
            <tr>
                <td class='detail_td1'>굿즈 종류</td>
                <td class='detail_td2'>{{ post.Board_gtype|cut:"["|cut:"'"|cut:"]" }}</td>
                
                <td class='detail_td1'>작성일</td>
                <td class='detail_td2'>{{post.Board_datetime}}</td>
            </tr>
            <tr>
                <td colspan='4' class='detail_title'>{{post.Board_title}}</td>
            </tr>
            <tr>
                <td colspan='4' class='detail_content'>{{post.Board_content|linebreaksbr|truncatechars:600}}</td>
            </tr>
        </table>
    </div>
    </div><div style="clear:both;overflow:auto;"></div>
    <div style='height:6%;'>
        <a class="btn btn-puple float-end" type="button" href="{% url 'articleapp:ListPost' %}"><iconify-icon icon="material-symbols:format-list-bulleted" style='font-size:0.8rem;'></iconify-icon>&nbsp;목록</a>
    </div>
    <div>
        <hr />
        <h4>댓글</h4>
        {% if post.comment_set.all %}
        <table>
            {% for comment in post.comment_set.all %}
            <tr>
                <td id = 'comment_content'><textarea rows='1' id = 'c_content' class='Content{{ comment.id }} text_area' disabled>{{ comment.Comment_content }}</textarea></td>
                <td id = 'comment_nad'>{{ comment.Comment_writer.nickname }}<input type = 'text' id = 'c_date' class='Date{{ comment.id }}' value='{{ comment.Comment_datetime }}' readonly></td>
                {% if request.user == comment.Comment_writer %}
                    <td id = 'comment_btn'>
                        <input type='button' class='Update{{ comment.id }} btn-outline-blue' onclick = 'Update({{ comment.id }});' value='수정'>
                        <input type="button" class="CommentSubmit{{ comment.id }} btn_blue" style="display:none" value="등록" onclick="CommentSubmit({{ comment.id }})">
                    </td>
                    <td id = 'comment_btn'>
                        <input type='button' class='Delete{{ comment.id }} btn-outline-red' onclick = "location.href = '{% url 'articleapp:DeleteComment' post.Board_id comment.id %}'" value='삭제'>
                        <input type="button" class="UpdateCancel{{ comment.id }} btn_gray" style="display:none" value="취소" onclick="UpdateCancel({{ comment.id }})">
                    </td>
                {% else %}
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                {% endif %}
            </tr>
            {% endfor %}
        </table>
        {% endif %}
        <hr />
        <form method='POST' action="{% url 'articleapp:CreateComment' post.Board_id %}">
            {% csrf_token %}
            <div style='width:85%;float:left;'>{{comment.Comment_content}}</div>
            <div style='width:15%;float:right;'><input type='submit' class="comment_submit btn btn-dark" value='댓글&#10;작성'></div><div style="clear:both;overflow:auto;"></div>
        </form>
    </div>
</div>
{% endblock %}

BP/article/templates/List_Post.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/article.css' %}">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.1/font/bootstrap-icons.css">
<div class='detail_body'>
    <div class="text-center mt-3">
        {% if user.is_authenticated %}
            <a class="btn btn-success float-end" type="button" href="{% url 'articleapp:CreatePost' %}"><i class="uil uil-pen"></i>&nbsp; 글쓰기</a>
        {% endif %}
    </div>
    <div style='margin-top: 1rem!important'>
        <h3>공유 게시판</h3>
    </div>
    <div class='b_info'>
        <hr />
        <span>공유 게시판 > 목록</span>
        <hr />
    </div>
    <form action="" class="my-4 form_st" method="get" enctype="form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col-2 text-center">
                <h5>공구여부</h5>
            </div>
            <div class="col align-middle">
                <input type="radio" name="search_share" value="희망" id="search_share0">
                <label class="mx-2" for="search_share0">희망</label>
                <input type="radio" name="search_share" value="비희망" id="search_share1">
                <label class="mx-2" for="search_share1">비희망</label>
            </div>
        </div>
        <div class="row">
            <div class="col-2 text-center">
                <h5>굿즈종류</h5>
            </div>
            <div class="col">
                <input type="checkbox" name="search_gtype" value="그립톡" id="search_gtype0">
                <label class="mx-2" for="search_gtype0">그립톡</label>
                <input type="checkbox" name="search_gtype" value="키링" id="search_gtype2">
                <label class="mx-2" for="search_gtype2">키링</label>
                <input type="checkbox" name="search_gtype" value="티셔츠" id="search_gtype3">
                <label class="mx-2" for="search_gtype3">티셔츠</label>
                <input type="checkbox" name="search_gtype" value="핸드폰케이스" id="search_gtype4">
                <label class="mx-2" for="search_gtype4">핸드폰케이스</label>
                <input type="checkbox" name="search_gtype" value="해당없음" id="search_gtype5">
                <label class="mx-2" for="search_gtype5">해당없음</label>
            </div>
        </div>
        <div class="row">
            <div class="col-2">
                <select name="search_type" id="search_tp" class="search_type w-100">
                    <option value="s_total">전체</option>
                    <option value="s_title">제목</option>
                    <option value="s_content">내용</option>
                    <option value="s_writer">작성자</option>
                </select>
            </div>
            <div class="col">
                <input type="search" value="{{ search }}" placeholder="검색어를 입력해주세요." name="searched" class="in_s p-2">
                <button class="btn btn-primary search_ed" type="submit"><i class="uil uil-search"></i>&nbsp; 검색</button>
            </div>
        </div>
    </form>
    <hr>
    <div class="MainGrid__StyledGrid-sc-1u1dl1e-0 gHAcDL styled-grid">
        {%if postlist%}
        <div class="row">
            {% for post in postlist %}
            <div class="col-3 my-2">
                <div>
                    <a class="card shadow"  href="{% url 'articleapp:DetailPost' post.Board_id %}">
                        {% for image in post.postimage.all %}
                            <div class="carousel-item {% if forloop.counter == 1 %} active {% endif %}">
                                <img class="card-img-top bd-placeholder-img" style="height:10rem; object-fit: cover;" role="img" src="{{ image.Board_image.url }}">
                            </div>
                        {% endfor %}
                            <div class="card-body">
                                <p class="card-title h4" href="{% url 'articleapp:DetailPost' post.Board_id %}">{{ post.Board_title|truncatechars:13 }}</p>
                                <div class="btn-group align-middle">
                                    공구&nbsp;
                                    {% if post.Board_share == '희망' %}
                                    <i class="bi bi-check-square-fill"style='font-size:1.1rem;color:green;padding-top:0.2rem;'></i>
                                    {% else %}
                                    <i class="bi bi-x-square-fill" style='font-size:1.1rem;color:red;padding-top:0.2rem;'></i>
                                    {% endif %}
                                </div>
                                <div>
                                    {% if '그립톡' in post.Board_gtype %}
                                    <span class="custom-control custom-switch badge">
                                        그립톡
                                    </span>
                                    {% endif %}
                                    {% if '키링' in post.Board_gtype %}
                                    <span class="custom-control custom-switch badge">
                                        키링
                                    </span>
                                    {% endif %}
                                    {% if '티셔츠' in post.Board_gtype %}
                                    <span class="custom-control custom-switch badge">
                                        티셔츠
                                    </span>
                                    {% endif %}
                                    {% if '핸드폰케이스' in post.Board_gtype %}
                                    <span class="custom-control custom-switch badge">
                                        핸드폰케이스
                                    </span>
                                    {% endif %}
                                    {% if '해당없음' in post.Board_gtype %}
                                    <span class="custom-control custom-switch badge">
                                        해당없음
                                    </span>
                                    {% endif %}
                                </div>
                                <div class="d-flex justify-content-between align-items-center mt-2">
                                    <div>
                                        <img src="{{post.Board_writer.profile.image.url}}"
                                        style="height:2rem; width:2rem; border-radius:1rem;">
                                        <small class="text-muted">{{ post.Board_writer.nickname }}</small>
                                    </div>
                                    <small class="text-muted">{{ post.Board_datetime|date:'Y-m-d' }}</small>
                                </div>
                            </div>
                    </a>
                    </div>
                </div>
            {% endfor %}
        </div>
        {% else %}
            <h5 style="text-align: center; font-size: 1rem;">게시글이 없습니다.</h5>
        {% endif %}
    </div>
</div>
{% endblock content %} 

BP/article/templates/Update_Post.html
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<script src="{% static 'js/article.js' %}"></script>
<link rel="stylesheet" href="{% static 'css/article.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"/>
<form class='form-control' method='post' enctype="multipart/form-data">
    {% csrf_token %}
    <div style='margin-top: 1rem!important'>
        <h3>공유 게시판</h3>
    </div>
    <div class='b_info'>
        <hr />
        <span>공유 게시판 > 글 수정</span>
        <hr />
    </div>
    <span style='font-size: 1.15rem;float:right;color:#848897;'><mark class="red">*</mark>표시는 필수 입력 항목입니다.</span>
    <div class='table-responsive'>
        <table class='create_table'>
            <tr>
                <td class='thst' height=36px;><mark class="red">*</mark>공구여부</td>
                <td class='tdst'>{{ post_form.Board_share }}</td>
            </tr>
            <tr>
                <td rowspan="2" class='thst' height=36px;><mark class="red">*</mark>굿즈종류</td>
                <td class='tdst'>{{ post_form.Board_gtype }}</td>
            </tr>
            <tr>
                <td class='tdst'>
                {% if post_form.Board_gtype.errors %}
                    <span style="color:red;}">{{post_form.Board_gtype.errors}}</span>
                {% endif %}</td>
            </tr>
            <tr>
                <td class='thst' height=36px;><mark class="red">*</mark>제목</td>
                <td class='tdst'>{{ post_form.Board_title }}</td>
            </tr>
            <tr>
                <td class='thst'><mark class="red">*</mark>내용</td>
                <td class='tdst'>{{ post_form.Board_content }}</td>
            </tr>
            <tr id = 'image'>
                <td class='thst' style='border-bottom:none;' rowspan='2'><mark class="red">*</mark>이미지 첨부</td>
            </tr>
            <tr>
                <td class='insert'>
                    {{ post_imageform.Board_image }}<div class="file-list"></div></td>
            </tr>
        </table>
    </div>
    <div style='text-align:center'><input class="btn btn-secondary" onClick = "location.href='{% url 'articleapp:DetailPost' postid %}'" type='button' value='취소'>&nbsp&nbsp<input class="btn btn-primary" type='submit' value='수정'></div>
</form>
{% endblock %}